### ISSUE TITLE
Suggestion: add the ability to set terrain to excluded from the FreezeMeltUtility

### ISSUE THREAD

**Issue by Poeteca** [GarwelGarwel/Celsius#43]
Adding the ability to exclude terrains from the FreezeMeltUtility in the terraindef should allow for the patches of novel non-water terrains from mods like Alpha Biomes and the Biomes! series more feasible.

**Comment by GarwelGarwel** [comment]
What do you mean by "non-water terrains" and what sorts of patches do they need? What are those terrains?

**Comment by Poeteca** [comment]
To clarify, I mean terrains that users would expect to have special termal properties, but would not be expected to freeze into ice or at all. 

Both mods I named add different versions of lava/magma (AB_LiquidLava) that should be slow change temprature but not freeze. Alpha biomes also adds in liquid propane (AB_PropaneLake) and tar (AB_Tar) which should also act differently than the default behaviour. There are also a few mods other than what I mentioned that add in water heated by volcanism, such as ReGrow and Mashed's Ashlands, which would not be expected to freeze but still act like water. 

As for what they need. Ideally they "just" need a way be flagged to be excluded from freezemelt utility. As for thermal properties, the lava and tar should have higher heat capacity than water while the propaane should have a much lower heat capacity than water. 

I don't know know much of an impart adding an additional check to the freezemult utility would have on performance or if it is already possible to do what I have asked for with the current version.

**Comment by GarwelGarwel** [comment]
Thanks for clarifying. Currently, Celsius tells that something is water simply by looking for the "Water" tag in TerrainDef, which is the vanilla-friendly way. With ice, it's even more straightforward, as there is only one kind of ice in vanilla.

The easiest option would be to add a "Freezable" tag, which would be used instead of "Water". But I see that some mods also add custom ice and packed snow terrains. So perhaps I should give it a bit more thought.

**Comment by GarwelGarwel** [comment]
Implemented Freezable and Meltable terrain tags in v2.3
